# version 9
name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Install Dependencies
        run: |
          npm ci

      - name: Verify Docker Setup
        run: docker version

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker build -t softa67/awshotelbackend:latest .
          docker login -u softa67 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push softa67/awshotelbackend:latest

      # - name: EC2 SCP > Copy / to /aws-hotel-server/
      #   uses: appleboy/scp-action@v0.1.4
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: "*"
      #     target: "aws-hotel-server/"

      - name: EC2 SSH > Start PM2 process
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u softa67 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
            docker pull softa67/awshotelbackend:latest
            docker run --rm -p -d 80:3000 softa67/awshotelbackend:latest

# version 8
# name: Deploy Backend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - name: Docker Setup Buildx
#         uses: docker/setup-buildx-action@v3.0.0

#       - name: Install Dependencies
#         run: |
#           npm ci

#       - name: Verify Docker Setup
#         run: docker version

#       - name: Build and Push Docker Image
#         run: |
#           docker buildx create --use
#           docker build -t softa67/awshotelbackend:latest .
#           docker login -u softa67 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
#           docker push softa67/awshotelbackend:latest

#       # - name: EC2 SCP > Copy / to /aws-hotel-server/
#       #   uses: appleboy/scp-action@v0.1.4
#       #   with:
#       #     host: ${{ secrets.EC2_HOST }}
#       #     username: ${{ secrets.SSH_USERNAME }}
#       #     key: ${{ secrets.SSH_PRIVATE_KEY }}
#       #     source: "*"
#       #     target: "aws-hotel-server/"

#       - name: EC2 SSH > Start PM2 process
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             docker login -u softa67 -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
#             docker pull softa67/awshotelbackend:latest
#           # script: |
#           #   cd /aws-hotel-server
#           #   pm2 start "server.js"

# seventh version
# name: Deploy Backend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - name: Docker Setup Buildx
#         uses: docker/setup-buildx-action@v3.0.0

#       - name: Install Dependencies
#         run: |
#           npm ci

#       - name: Setup Docker
#         uses: actions/setup-docker@v4
#         with:
#           dockerfile: .aws-hotel-server/Dockerfile

#       - name: Build and Push Docker Image
#         run: docker build -t softa67/awshotelbackend:latest . && docker push softa67/awshotelbackend:latest

#       - name: EC2 SCP > Copy / to /aws-hotel-server/
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "*"
#           target: "aws-hotel-server/"

#       - name: EC2 SSH > Start PM2 process
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /aws-hotel-server
#             pm2 start "server.js"

# sixth version
# name: Deploy Backend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - name: Install Dependencies
#         run: |
#           npm ci

#       - name: Setup Docker
#         uses: actions/setup-docker@v4
#         with:
#           dockerfile: .aws-hotel-server/Dockerfile

#       - name: Build and Push Docker Image
#         run: docker build -t softa67/awshotelbackend:latest . && docker push softa67/awshotelbackend:latest

#       - name: EC2 SCP > Copy / to /aws-hotel-server/
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "*"
#           target: "aws-hotel-server/"

#       - name: EC2 SSH > Start PM2 process
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /aws-hotel-server
#             pm2 start "server.js"

# fifth version
# name: Deploy Backend

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - name: Install Dependencies
#         run: |
#           npm ci

#       - name: EC2 SCP > Copy / to /aws-hotel-server/
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "*"
#           target: "aws-hotel-server/"

#       - name: EC2 SSH > Start PM2 process
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /aws-hotel-server
#             pm2 start "server.js"

# fourth version
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # - name: Configure AWS credentials
#       #   run: |
#       #     echo "[default]
#       #     aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
#       #     aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - name: Install Dependencies
#         run: |
#           npm ci

#       - name: EC2 SCP > Copy / to /aws-hotel-server/
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "*"
#           target: "aws-hotel-server/"

#       - name: EC2 SSH > Start PM2 process
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /aws-hotel-server
#             pm2 start "server.js"

# third version
# on: [push]
# branches:
#   - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # - name: Configure AWS credentials
#       #   run: |
#       #     echo "[default]
#       #     aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
#       #     aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 18

#       - name: Install Dependencies
#         run: |
#           npm ci

#       - name: EC2 SCP > Copy / to /aws-hotel-server/
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "*"
#           target: "aws-hotel-server/"

#       - name: EC2 SSH > Start PM2 process
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#       script: |
#             cd /aws-hotel-server
#             pm2 start "server.js"

# second version
# on: [push]
# branches:
#   - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         run: |
#           echo "[default]
#           aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials

#          - name: Setup NodeJS
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#        - name: Install Dependencies
#               run: |
#               npm ci

# - name: EC2 SCP > Copy /dist to /aws-hotel-server/dist
#         uses: appleboy/scp-action@v0.1.4
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           target: "aws-hotel-server/"

#       - name: EC2 SSH > Start PM2 process (with injected db connection string)
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
# script: |
# #   pm2 start "server.js" --name aws-hotel-serverapi

# first version
# name: Backend EC2 Deployment

# on: [push]
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         run: |
#           echo "[default]
#           aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials

#       - name: Install dependencies
#         run: |
#           # Add commands to install dependencies (e.g., Node.js, npm, etc.)

#       - name: Deploy to EC2
#         run: |
#           # Add commands to deploy your backend to the EC2 instance

